### ISSUE TITLE
Command Window won't recognize requirements.txt file.

### ISSUE THREAD

**Issue by Obsidian2498** [MrReplikant/Project-Replikant#1]
Hello! I'm trying to set up your program and the directions were very easy to follow, but I've hit a snag.

When I open the command window and type in the "pip install -r requirements.txt", it keeps giving me an error message saying that such a file doesn't exist in my directory, even though I have the File Directory pulled up and I'm staring at the exact same tile it's saying isn't there?

Do you possibly know what I'm doing wrong?

Thankful for your hard work,

Obsidian
![CommandWindowScreenshot](https://user-images.githubusercontent.com/88219829/127726791-c58d20e1-6e48-4a1f-bef1-7169bc81228d.png)

**Comment by MrReplikant** [comment]
> Hello! I'm trying to set up your program and the directions were very easy to follow, but I've hit a snag.
> 
> When I open the command window and type in the "pip install -r requirements.txt", it keeps giving me an error message saying that such a file doesn't exist in my directory, even though I have the File Directory pulled up and I'm staring at the exact same tile it's saying isn't there?
> 
> Do you possibly know what I'm doing wrong?
> 
> Thankful for your hard work,
> 
> Obsidian
> ![CommandWindowScreenshot](https://user-images.githubusercontent.com/88219829/127726791-c58d20e1-6e48-4a1f-bef1-7169bc81228d.png)
> 

Make sure you've opened the Project Replikant file in CMD, it's saying in the screenshot that you're trying to do this directly from your c drive, so it doesn't see the file because as far as CMD can see, it isn't there! Hope this answers your question!

**Comment by Obsidian2498** [comment]
It did, thank you! I'm starting to get a whole new error now, but the first issue was definitely fixed, thank you!
![CommandWindowScreenshot1](https://user-images.githubusercontent.com/88219829/127727599-39fc556f-8166-4ab7-b568-30d31a93097f.png)

**Comment by MrReplikant** [comment]
That one seems to happen often, sadly enough.  Have you tried 1.12.0? Open the requirements file and change it to that version, and see if it fixes it. If so, feel free to fork and make a pull request!

**Comment by Obsidian2498** [comment]
Unfortunately, that was no good. Same error, just a different number.
![CommandWindowScreenshot2](https://user-images.githubusercontent.com/88219829/127728207-240b644a-cb50-48e1-ba4c-cab2a6bcc073.png)

**Comment by MaverickMartyn** [comment]
I had this same problem..
I managed to fix it by removing all my Python installations and the Py launcher.
I then installed the specific version mentioned in the README.md file.
It was late yesterday, but if I recall correctly, later versions of the PIP package manager does not have the older 1.X.X versions of the required Tensorflow package.

**Comment by Obsidian2498** [comment]
> I had this same problem..
> I managed to fix it by removing all my Python installations and the Py launcher.
> I then installed the specific version mentioned in the README.md file.
> It was late yesterday, but if I recall correctly, later versions of the PIP package manager does not have the older 1.X.X versions of the required Tensorflow package.

That worked!! Thank you very much for your help!
