### ISSUE TITLE
Can't get Program to Run

### ISSUE THREAD

**Issue by Jff007** [MrReplikant/Project-Replikant#5]
Hey, so I followed the instructions exactly for the Windows install, but I can't get the program to run. I click on play.py and a CMD window opens for a split-second, then closes again.

Any ideas on troubleshooting?

My PC is a Ryzen 3800X, 2080TI, 32GB RAM.

**Comment by MrReplikant** [comment]
Which Branch are you using? Master or the Experimental Branch? 

It could be a wide variety of things. Are you running play.py outside of the folder, or are you keeping it inside the source code folder?

**Comment by Jff007** [comment]
Mainline release 1.2

I've kept it within the source folder. All my other Python programs run properly, this one just refuses to open for some odd reason. 

I've tried full uninstalls and reinstalls three times now. I'll try a fourth and update accordingly.

**Comment by Jff007** [comment]
Well, this is somewhat embarassing, on the fifth reinstall, everything started functioning perfectly. I guess I'll chalk it up to Windows 10 being Windows 10. 

Good job on the program so far! I'm excited to see where it goes!
